#!/bin/bash
set -euo pipefail

# Import OSM PBF data into Barrelman PostGIS database (db-only steps).
# Run this inside the barrelman-db container, or via scripts/run-import.sh
# from the host which also handles the bun steps in the barrelman container.
#
# Usage:
#   # From host (recommended):
#   ./scripts/run-import.sh
#
#   # Directly inside db container:
#   docker exec -e DATABASE_URL=... barrelman-db bash /app/scripts/import-osm.sh
#
# Environment variables:
#   DATABASE_URL          - PostgreSQL connection string (required)
#   GEOFABRIK_URL         - PBF download URL (default: NC extract)
#   IMPORT_PBF            - Path to local PBF file, overrides download
#   BARRELMAN_DATA_DIR    - Data directory path (default: /data inside container,
#                           or <project>/data when running locally)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# BARRELMAN_DATA_DIR is set to /data in the Docker image; fall back to project/data locally
DATA_DIR="${BARRELMAN_DATA_DIR:-$PROJECT_DIR/data}"

GEOFABRIK_URL="${GEOFABRIK_URL:-https://download.geofabrik.de/north-america/us/north-carolina-latest.osm.pbf}"
PBF_FILE="${IMPORT_PBF:-${1:-$DATA_DIR/region.osm.pbf}}"

DATABASE_URL="${DATABASE_URL:?DATABASE_URL is required}"

mkdir -p "$DATA_DIR"

# Step 1: Download PBF if not present
if [ ! -f "$PBF_FILE" ]; then
    echo "Downloading PBF from $GEOFABRIK_URL..."
    wget -q --show-progress -O "$PBF_FILE" "$GEOFABRIK_URL"
    echo "Download complete: $(du -h "$PBF_FILE" | cut -f1)"
else
    echo "Using existing PBF: $PBF_FILE ($(du -h "$PBF_FILE" | cut -f1))"
fi

# Step 2: Import with osm2pgsql flex output
echo "Running osm2pgsql import..."
osm2pgsql \
    --create \
    --slim \
    --flat-nodes="$DATA_DIR/nodes.cache" \
    --output=flex \
    --style="$PROJECT_DIR/import/osm2pgsql-flex.lua" \
    -d "$DATABASE_URL" \
    "$PBF_FILE"

echo "osm2pgsql import complete."

# Step 3: Post-import SQL (extract structured fields, build indexes)
echo "Running post-import SQL..."
psql "$DATABASE_URL" -f "$PROJECT_DIR/import/post-import.sql"

# Step 4: Rebuild tsvector (abbreviations are generated by the barrelman container — see run-import.sh)
echo "Rebuilding tsvector..."
psql "$DATABASE_URL" -c "
UPDATE geo_places SET ts = to_tsvector('simple', unaccent(
    coalesce(name, '') || ' ' || coalesce(name_abbrev, '')
))
WHERE name IS NOT NULL;"

echo "DB import steps complete. Run scripts/run-import.sh to also build abbreviations."
