"""tools.pipeline_dials — the always-current dial manifest.

Prints every config field across shapesnap / linegraph / lineorder /
segments (name, default, type, docstring/inline comment) grouped by stage,
read straight from the source so values never drift. Also refreshes
``docs/pipeline-dials.md`` from the same data.

  uv run --with-requirements segments/requirements.txt \
      python -m tools.pipeline_dials            # human-readable + refresh doc
  python -m tools.pipeline_dials --json         # machine-readable
  python -m tools.pipeline_dials --no-doc       # skip the doc refresh

No DB, no build — pure source introspection (fast, dependency-free).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.dials import REPO_ROOT, collect  # noqa: E402

DOC_PATH = REPO_ROOT / "docs" / "pipeline-dials.md"


def _wrap(text: str, width: int, indent: str) -> list[str]:
    if not text:
        return []
    words = text.split()
    lines, cur = [], indent
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = indent + w + " "
        else:
            cur += w + " "
    if cur.strip():
        lines.append(cur.rstrip())
    return lines


def render_text(groups) -> str:
    out: list[str] = []
    out.append("PIPELINE DIALS — every config field (default | type)")
    out.append("source-introspected; run again after any dataclass edit\n")
    for stage, clsname, dials in groups:
        out.append(f"══ {stage}  ·  {clsname} ══")
        if not dials:
            out.append("  (no fields)")
            out.append("")
            continue
        for d in dials:
            default = d.default if len(d.default) <= 60 else d.default[:57] + "…"
            typ = f"  [{d.type}]" if d.type and d.type != "table" else ""
            out.append(f"  {d.name} = {default}{typ}")
            out.extend(_wrap(d.doc, 78, "      "))
        out.append("")
    return "\n".join(out)


def render_markdown(groups) -> str:
    out: list[str] = []
    out.append("# Pipeline dials — auto-generated manifest\n")
    out.append("Generated by `python -m tools.pipeline_dials` — **do not edit "
               "by hand**. Every field of every pipeline config dataclass "
               "(plus the shapesnap graph tag tables), read from source so the "
               "values never drift. The narrative for *why* each dial exists "
               "lives in `docs/transit-tuning-log.md`.\n")
    for stage, clsname, dials in groups:
        out.append(f"## {stage}\n")
        out.append(f"`{clsname}`\n")
        out.append("| dial | default | type | what it does |")
        out.append("|------|---------|------|--------------|")
        for d in dials:
            default = d.default.replace("|", "\\|").replace("\n", " ")
            if len(default) > 70:
                default = default[:67] + "…"
            typ = "" if d.type == "table" else d.type
            doc = d.doc.replace("|", "\\|") or "—"
            out.append(f"| `{d.name}` | `{default}` | {typ} | {doc} |")
        out.append("")
    return "\n".join(out)


def to_json(groups) -> str:
    payload = []
    for stage, clsname, dials in groups:
        payload.append({
            "stage": stage,
            "config": clsname,
            "dials": [
                {"name": d.name, "default": d.default, "type": d.type,
                 "doc": d.doc}
                for d in dials
            ],
        })
    return json.dumps(payload, indent=2)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--json", action="store_true", help="machine-readable")
    ap.add_argument("--no-doc", action="store_true",
                    help="do not refresh docs/pipeline-dials.md")
    args = ap.parse_args(argv)

    groups = collect()
    if args.json:
        print(to_json(groups))
        return 0

    print(render_text(groups))
    if not args.no_doc:
        DOC_PATH.write_text(render_markdown(groups) + "\n")
        n = sum(len(d) for _s, _c, d in groups)
        print(f"[pipeline_dials] refreshed {DOC_PATH.relative_to(REPO_ROOT)} "
              f"({n} dials across {len(groups)} configs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
